name: Zip and Release
on:
  push:
    tags:
       - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'pre') }}
    steps:
      - uses: actions/checkout@v3
      - name: Archive Release1
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'development_behavior_packs/NIA_V4.0_BP'
          path: '.'
          filename: NIAV4BP-${{ github.ref_name }}.zip
      - name: Archive Release2
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'development_resource_packs/NIA_V4.0_RP'
          path: '.'
          filename: NIAV4RP-${{ github.ref_name }}.zip
      - name: Archive Release3
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: '.'
          path: 'NIA-Server'
          filename: NIA-Server-${{ github.ref_name }}.zip
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "development_behavior_packs/NIA_V4.0_BP/NIAV4BP-${{ github.ref_name }}.zip,development_resource_packs/NIA_V4.0_RP/NIAV4RP-${{ github.ref_name }}.zip,NIA-Server-${{ github.ref_name }}.zip,world_behavior_packs.json,world_resource_packs.json"
          bodyFile: "CHANGELOG.md"
          generateReleaseNotes: false
          token: ${{ secrets.GITHUB_TOKEN }}